apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.backend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}

      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.backend.port }}"
        prometheus.io/path: "/metrics"

    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.backend.port }}
              name: http

          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret