frontend:
  name: frontend
  enabled: true
  image:
    repository: khrisblurp/blood-app-frontend
    tag: v2
  replicas: 1
  containerPort: 80
  service:
    type: NodePort
    port: 80
    nodePort: 30007
  env:
    REACT_APP_API_URL: http://backend:8000

backend:
  name: backend
  image:
    repository: khrisblurp/blood-app-backend
    tag: latest
  replicas: 1
  port: 8000
  servicePort: 8000

postgres:
  enabled: true
  name: postgres
  image: postgres:15
  port: 5432
  storage: 1Gi
  username: postgres
  password: #change  me
  db: mydb